
<script src="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/js/jquery-3.2.1.js"></script>
<script src="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/js/tether/tether.js"></script>
<script src="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/js/bootstrap.js"></script>
<script src="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/js/script.js"></script>
</body>
</html>