<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/img/png/fav_icon.png" rel="shortcut icon"/>
    <link href="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/css/tether/tether.css" rel="stylesheet"/>
    <link href="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/css/bootstrap/bootstrap.css" rel="stylesheet"/>
    <link href="<?php echo $constants['user']['APP_CONFIG']['default']['WEB']['SITE_URL'];?>/css/styles.css" rel="stylesheet"/>
    <title>Sys Blog - <?php echo $title; ?></title>
</head>
<body class="container">
    <div class="<?php if(array_key_exists('error', $constants['system']['REQUEST']['SESSION'])) {
        echo "session-error";
    }?>">
        <?php
            if(array_key_exists('error', $constants['system']['REQUEST']['SESSION'])) {
                echo $constants['system']['REQUEST']['SESSION']['error'];
            }
        ?>
    </div>
    <div class="<?php if(array_key_exists('success', $constants['system']['REQUEST']['SESSION'])) {
            echo "session-success";
        }?>">
        <?php
        if(array_key_exists('success', $constants['system']['REQUEST']['SESSION'])) {
            echo $constants['system']['REQUEST']['SESSION']['success'];
        }
        ?>
    </div>