<div id="loginPageContainer" class="col-5">
    <div id="pageHead" class="col-12"><?php echo $title; ?></div>
    <div id="formContainer" class="col-12">
        <form enctype="application/x-www-form-urlencoded" action="register" method="post" id="registerForm" name="registerForm">
            <div class="form-group">
                <label class="row">
                    <div class="col-3"> Email: </div>
                    <div class="col-9"> <input type="email" class="form-control" name="email" placeholder="Please Enter your email here" required/> </div>
                </label>
            </div>
            <div class="form-group">
                <label class="row">
                    <div class="col-3"> Name: </div>
                    <div class="col-9"> <input type="text" class="form-control" name="name" placeholder="Please Enter your name here" maxlength="20" pattern="^[a-zA-Z]+(\s)?[a-zA-Z]*$" required/> </div>
                </label>
            </div>
            <div class="form-group">
                <label class="row">
                    <div class="col-3"> Password: </div>
                    <div class="col-9"> <input type="password" class="form-control" name="password" placeholder="Please Enter your password" minlength="8" required/> </div>
                </label>
            </div>
            <div class="form-group">
                <label class="row">
                    <div class="col-3"> Confirm Password: </div>
                    <div class="col-9"> <input type="password" class="form-control" name="confirm_password" placeholder="Please re-enter your password" minlength="8" required/> </div>
                </label>
            </div>
            <div class="form-group">
                <label class="row">
                    <div class="col-12 form-submit-label"> Submit your information </div>
                    <!-- Form will not submit using $.submit() when name is submit because forms property submit will name replaced by the complete element if name is submit -->
                    <div class="col-12 form-submit-button"> <input type="submit" class="form-control btn btn-outline-primary col-12" name="register" onclick="validateForm()" value="Register"/> </div>
                </label>
            </div>
        </form>
    </div>
</div>