<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
//        'App\Model' => 'App\Policies\ModelPolicy',
        \App\Post::class => \App\Policies\PostP::class
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();
        \Gate::before(function($user, $ability) {
            echo "<br/>inside Gate bfore<br/>";
        });

        \Gate::define('updatepost', function($user, $post) {
            echo "<br/> inside update gate callback <br/>";
            return false;
        });

        \Gate::after(function($user, $ability) {
            echo "<br/>inside Gate after<br/>";
        });
//
        \Gate::define('authPost', 'App\Classes\authorizePostGate@auth');
        \Gate::define('views', 'App\Classes\PostGateResource@views');
//
        \Gate::resource('post', 'App\Classes\PostGateResource');

        \Laravel\Passport\Passport::routes();
        \Laravel\Passport\Passport::tokensCan([
            'place-orders' => 'Place orders',
            'check-status' => 'Check order status',
        ]);

        \Laravel\Passport\Passport::tokensExpireIn(\Carbon\Carbon::now()->addYears(20));//You can also use addDays(10)
        \Laravel\Passport\Passport::refreshTokensExpireIn(\Carbon\Carbon::now()->addYears(20));//You can also use addDays(10)
//        \Laravel\Passport\Passport::pruneRevokedTokens(); //basic garbage collector





        //
    }

    public function register() {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
