<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="<?php echo $viewHelper -> resourceUrl("png/fav_icon.png","img")?>" rel="shortcut icon"/>
    <link href="<?php echo $viewHelper -> resourceUrl("tether/tether.css","css")?>" rel="stylesheet"/>
    <link href="<?php echo $viewHelper -> resourceUrl("bootstrap/bootstrap.css","css")?>" rel="stylesheet"/>
    <link href="<?php echo $viewHelper -> resourceUrl("styles.css","css")?>" rel="stylesheet"/>
    <title>Sys Blog - <?php echo $title; ?></title>
</head>
<body class="container">
<?php
if(array_key_exists('error', $constants['system']['REQUEST']['SESSION'])) {
?>
<div class="session-error">
    <?php
    echo $constants['system']['REQUEST']['SESSION']['error'];
    }
    ?>
</div>
<?php
if(array_key_exists('success', $constants['system']['REQUEST']['SESSION'])) {
?>
<div class="session-success">
    <?php
    echo $constants['system']['REQUEST']['SESSION']['success'];
    }
    ?>
</div>